# Global settings that apply to all jobs unless overridden
global:
  # How frequently Prometheus will scrape its targets
  scrape_interval: 15s     # Default scrape interval
  
  # How frequently Prometheus will evaluate rules (like alerts)
  evaluation_interval: 15s  # Evaluate rules every 15s

# List of targets for Prometheus to scrape
scrape_configs:
  # Job for scraping metrics from our orderbook application
  - job_name: 'orderbook_client'
    static_configs:
      # Where to find our application's metrics
      # This should point to where our MetricsCollector is exposing metrics
      # If running locally, use 'localhost:2112' or your machine's IP (192.168.5.205:2112)
      - targets: ['192.168.5.205:2112']  # CHANGE THIS TO YOUR APP'S IP/PORT
    
    # Path where metrics are exposed (matches our MetricsCollector's endpoint)
    metrics_path: '/metrics'
    
    # Override global scrape interval for this job
    # More frequent updates for order book metrics
    scrape_interval: 5s    

  # Job for scraping Prometheus's own metrics
  - job_name: 'prometheus'
    static_configs:
      # Where the Prometheus server itself is running
      # This is the Prometheus server's IP address (192.168.5.142)
      - targets: ['192.168.5.142:9090']