global:
  scrape_interval: 15s     # Default scrape interval
  evaluation_interval: 15s  # Evaluate rules every 15s

scrape_configs:
  - job_name: 'orderbook_client'
    static_configs:
      - targets: ['localhost:2112']
    metrics_path: '/metrics'
    scrape_interval: 5s    # More frequent scraping for this job

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 