// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	common "github.com/alejoacosta74/kraken-api/internal/common"
	gomock "github.com/golang/mock/gomock"
)

// MockBus is a mock of Bus interface.
type MockBus struct {
	ctrl     *gomock.Controller
	recorder *MockBusMockRecorder
}

// MockBusMockRecorder is the mock recorder for MockBus.
type MockBusMockRecorder struct {
	mock *MockBus
}

// NewMockBus creates a new mock instance.
func NewMockBus(ctrl *gomock.Controller) *MockBus {
	mock := &MockBus{ctrl: ctrl}
	mock.recorder = &MockBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBus) EXPECT() *MockBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockBus) Publish(topic common.MessageType, event interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", topic, event)
}

// Publish indicates an expected call of Publish.
func (mr *MockBusMockRecorder) Publish(topic, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBus)(nil).Publish), topic, event)
}

// Subscribe mocks base method.
func (m *MockBus) Subscribe(topic common.MessageType) <-chan interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", topic)
	ret0, _ := ret[0].(<-chan interface{})
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBusMockRecorder) Subscribe(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBus)(nil).Subscribe), topic)
}

// Unsubscribe mocks base method.
func (m *MockBus) Unsubscribe(topic common.MessageType, ch <-chan interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", topic, ch)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockBusMockRecorder) Unsubscribe(topic, ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockBus)(nil).Unsubscribe), topic, ch)
}
